### ISSUE TITLE
Example snippets show PHP SDK v4.0 API

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#509]
The [Graph API reference docs](https://developers.facebook.com/docs/graph-api/reference/) show the code snippets for v4.0 even though there's a comment above it saying that it's v5.

![Docs error](https://dl.dropboxusercontent.com/u/497055/screenshots/docs-error-php-sdk-4.png)

Not sure how to send a PR for that one. :)

**Comment by stefanledin** [comment]
I've been struggling with this for a couple of days now. Copy/paste from the documentation results in errors about the `execute()` method which doesn't exist in the request object. 
I had to dive into the source in order to hack together a working solution. The documentation is just confusing right now :/

**Comment by SammyK** [comment]
Hey @gfosco! How do you want to handle documentation changes going forward? :)

**Comment by SpaHost** [comment]
More than 1 year... and still happening

**Comment by SammyK** [comment]
Hey @viv001! What would be involved with updating the snippets in the documentation? Is there anything I can do to help with this one? :)

**Comment by viv001** [comment]
Hey @SammyK, we are thinking of moving away from Facebook's external documentation for this SDK. We should have the documentation on GitHub and a link to it on Facebook's documentation page. Do you think that's feasible?

**Comment by SammyK** [comment]
Hey @viv001! Just want to make sure I understand correctly, we want to move the docs back to Facebook doc website? Or we want to point the Facebook docs pages to the SDK?

**Comment by viv001** [comment]
We want to point the Facebook docs to the SDK. So, any doc changes can be made on github without having to change Facebook's docs.

**Comment by SammyK** [comment]
Sounds good! Is there anything I can do to help with this?

**Comment by viv001** [comment]
I think we just have to make changes on Facebook's end since the up-to-date docs are already on Github. I shall talk to our team here and keep you updated through this task :)

**Comment by yguedidi** [comment]
@viv001 any news on this one? :)

**Comment by viv001** [comment]
This is fixed https://developers.facebook.com/docs/php/gettingstarted :)

**Comment by SammyK** [comment]
Thanks @viv001! It's still showing the v4 syntax in the [code snippets at the top](https://developers.facebook.com/docs/graph-api/reference/v2.9/achievement#read) even though the comment says it's for v5.

<img width="711" alt="screen shot 2017-04-30 at 1 21 26 pm" src="https://cloud.githubusercontent.com/assets/578780/25566880/530042ec-2da8-11e7-9622-be6fbd49d0b5.png">

**Comment by yguedidi** [comment]
ping @viv001 :)

**Comment by viv001** [comment]
Hi folks, sorry I wasn't getting notified about these pings for some reason - We are now working to get this removed from our page completely and just point to the github repo docs. I will loop back on this as soon as I have an update.

**Comment by yguedidi** [comment]
@viv001 Thank you!! Is it possible for @SammyK and I to have full access on this repo as we are the maintainers since years now? :)

**Comment by viv001** [comment]
@yguedidi For sure! I will just get the final approvals from our internal Open Source team and we should be good to go. 
On a related note, I am not able to access settings for this repo anymore ; it doesn't seem like I am the admin - is there any way to confirm this?

**Comment by SammyK** [comment]
Thanks @viv001! Yeah, I'm not able to assign issues to you so I'm guessing you're not admin of the repo anymore?

**Comment by gfosco** [comment]
I added @viv001 back as an Admin on this repo.

**Comment by yguedidi** [comment]
Thanks @viv001 and @gfosco !!! :)

**Comment by SammyK** [comment]
This finally got updated! Yay! Thanks! :D
